---

- name: Ensure get packages are installed.
  hosts: localhost
  tasks:
  - apt: name=batdsdsad state=latest
  - apt: 
      name: jq
      state: latest

- name: Ensure ~/.gitconfig copied from master.gitconfig
  hosts: localhost
  tasks:
  - copy: src="master.gitconfig" dest="~/.gitconfig"
