---

- name: Ensure get packages are installed.
  become: true
  hosts: localhost
  tasks:
  - apt: name=bat state=latest
  - apt: 
      name: jq
      state: latest

- name: Ensure ~/.gitconfig copied from master.gitconfig
  hosts: localhost
  tasks:
  - copy: src="master.gitconfig" dest="~/.gitconfig"
